In [2]:
import pandas as pd

In [47]:
cards = pd.read_csv('data/cards_merged.csv')

In [51]:
print(cards.isnull().sum())
cards.loc[cards['maxEvolutionLevel'].isnull(), 'maxEvolutionLevel'] = 0
cards.describe()

name                  0
id                    0
maxEvolutionLevel     0
elixirCost            1
rarity                0
damage11             29
hitpoints            20
type                  1
mobility              1
targets               1
attack_type           2
groupCard             1
usage                 2
Win Rate              2
dtype: int64

,id,maxEvolutionLevel,elixirCost,damage11,hitpoints,usage,Win Rate
count,1.210000e+02,121.000000,120.000000,92.000000,101.000000,119.000000,119.000000
mean,2.648764e+07,0.512397,3.975000,428.619565,1264.435644,5.337143,53.292605
std,7.970185e+05,0.731616,1.541921,444.015786,1024.305320,6.127417,3.805675
min,2.600000e+07,0.000000,1.000000,0.000000,81.000000,0.160000,43.880000
25%,2.600003e+07,0.000000,3.000000,192.750000,560.000000,1.760000,50.975000
50%,2.600006e+07,0.000000,4.000000,265.500000,1000.000000,3.280000,53.230000
75%,2.700000e+07,1.000000,5.000000,518.250000,1697.000000,7.280000,56.205000
max,2.800003e+07,3.000000,9.000000,2580.000000,5120.000000,42.880000,61.780000

In [14]:
cards.head()

,name,id,maxEvolutionLevel,elixirCost,rarity,damage11,hitpoints,type,mobility,targets,attack_type,groupCard,usage,Win Rate
0,Knight,26000000,3.0,3.0,common,202.0,1766.0,troop,ground,ground,single,False,8.88,51.79
1,Archers,26000001,1.0,3.0,common,214.0,304.0,troop,ground,both,single,True,1.44,46.10
2,Goblins,26000002,2.0,2.0,common,360.0,202.0,troop,ground,ground,single,True,3.60,54.32
3,Giant,26000003,2.0,5.0,rare,254.0,4090.0,troop,ground,buildings,single,False,2.32,59.10
4,P.E.K.K.A,26000004,1.0,7.0,epic,816.0,3760.0,troop,ground,ground,single,False,3.28,50.61

In [32]:
cards.info()
# replacing null values in order to convert datatypes
cards = cards.fillna(-999)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 121 entries, 0 to 120
Data columns (total 14 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   name               121 non-null    object
 1   id                 121 non-null    int64
 2   maxEvolutionLevel  48 non-null     float64
 3   elixirCost         120 non-null    float64
 4   rarity             121 non-null    object
 5   damage11           92 non-null     float64
 6   hitpoints          101 non-null    float64
 7   type               120 non-null    object
 8   mobility           120 non-null    object
 9   targets            120 non-null    object
 10  attack_type        119 non-null    object
 11  groupCard          120 non-null    object
 12  usage              119 non-null    float64
 13  Win Rate           119 non-null    float64
dtypes: float64(6), int64(1), object(7)
memory usage: 13.4+ KB

In [34]:
# converting datatype of numeric columns with no non-integer values
cards.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 121 entries, 0 to 120
Data columns (total 14 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   name               121 non-null    object
 1   id                 121 non-null    int64
 2   maxEvolutionLevel  121 non-null    int64
 3   elixirCost         121 non-null    int64
 4   rarity             121 non-null    object
 5   damage11           121 non-null    int64
 6   hitpoints          121 non-null    int64
 7   type               121 non-null    object
 8   mobility           121 non-null    object
 9   targets            121 non-null    object
 10  attack_type        121 non-null    object
 11  groupCard          121 non-null    object
 12  usage              121 non-null    float64
 13  Win Rate           121 non-null    float64
dtypes: float64(2), int64(5), object(7)
memory usage: 13.4+ KB

In [44]:
print(cards['rarity'].unique())
print(cards['type'].unique())
print(cards['mobility'].unique())
print(cards['targets'].unique())
print(cards['attack_type'].unique())
print(cards['rarity'].value_counts())
print(cards['type'].value_counts())
print(cards['mobility'].value_counts())
print(cards['targets'].value_counts())
print(cards['attack_type'].value_counts())

['common' 'rare' 'epic' 'legendary' 'champion']
['troop' 'building' 'spell' -999]
['ground' 'flying' 'both' -999]
['ground' 'both' 'buildings' -999]
['single' 'splash' -999]
rarity
epic         33
rare         30
common       29
legendary    21
champion      8
Name: count, dtype: int64
type
troop       86
spell       22
building    12
-999         1
Name: count, dtype: int64
mobility
ground    103
flying     16
both        1
-999        1
Name: count, dtype: int64
targets
ground       56
both         49
buildings    15
-999          1
Name: count, dtype: int64
attack_type
single    75
splash    44
-999       2
Name: count, dtype: int64

In [55]:
cards.loc[cards['attack_type'].isnull()]

,name,id,maxEvolutionLevel,elixirCost,rarity,damage11,hitpoints,type,mobility,targets,attack_type,groupCard,usage,Win Rate
104,Mirror,28000006,0.0,NaN,epic,0.0,NaN,spell,both,both,NaN,False,1.84,44.18
119,Spirit Empress,28000025,0.0,6.0,legendary,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [79]:
card_dum = cards.copy().drop(index = [104, 119])
card_dum['groupCard'] = card_dum['groupCard'].replace('True', 1).replace('False', 0)
card_dum['attack_type'] = card_dum['attack_type'].replace('splash', 1).replace('single', 0)
card_dum['rarity'] = card_dum['rarity'].replace('common', 0).replace('rare', 1).replace('epic', 2).replace('legendary', 3).replace('champioin', 4)
card_dum = cards.astype({'maxEvolutionLevel': 'int',
                         'elixirCost': 'int',
                         'damage11': 'int',
                         'hitpoints': 'int',
                         'groupCard': 'int',
                         'attack_type': 'int',
                         'rarity': 'int',
                         'groupCard': 'int'
                        })

/var/folders/5v/jcj2bhpn0mnbw8t66vnh8l180000gn/T/ipykernel_2029/1565955611.py:3: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  card_dum['attack_type'] = card_dum['attack_type'].replace('splash', 1).replace('single', 0)

IntCastingNaNError: Cannot convert non-finite values (NA or inf) to integer: Error while type casting for column 'elixirCost'

In [80]:
card_dum = pd.get_dummies(card_dum, columns = ['type', 'mobility', 'targets'], drop_first = True, dtype = int)
card_dum.head()

,name,id,maxEvolutionLevel,elixirCost,rarity,damage11,hitpoints,attack_type,groupCard,usage,Win Rate,type_spell,type_troop,mobility_ground,targets_buildings,targets_ground
0,Knight,26000000,3.0,3.0,0,202.0,1766.0,0,False,8.88,51.79,0,1,1,0,1
1,Archers,26000001,1.0,3.0,0,214.0,304.0,0,True,1.44,46.10,0,1,1,0,0
2,Goblins,26000002,2.0,2.0,0,360.0,202.0,0,True,3.60,54.32,0,1,1,0,1
3,Giant,26000003,2.0,5.0,1,254.0,4090.0,0,False,2.32,59.10,0,1,1,1,0
4,P.E.K.K.A,26000004,1.0,7.0,2,816.0,3760.0,0,False,3.28,50.61,0,1,1,0,1